### ISSUE TITLE
Fault codes and power

### ISSUE THREAD

**Issue by artelse** [zxdavb/incomfort-client#3]
Am working on implementing a javascript (+php) client version, so it can run in the browser. This largely works already, but I wonder about two things for now:
1. how do you derive Fault codes from the json response and
2. how does the official intergas incomfort client get information on usage and realtime power used?

Intergas might get some info by accumulation on their cloud service? The heater I bought second hand reported a use of 5000 hours, but was never connected to their service. Is there more info to get from lan2rf perhaps?

**Comment by zxdavb** [comment]
> how do you derive Fault codes from the json response and

Ah! It looks like a bug in the code:
https://github.com/zxdavb/incomfort-client/blob/ff758f4f0e084eaa7a1376c3f80760997f3927d4/incomfortclient/__init__.py#L254-L256

... should be:
```python
return self._data["fault_code"] if self.is_failed else None 
```

> how does the official intergas incomfort client get information on usage and realtime power used

The Heater sends a lot more data to Intergas (via the Gateway) than the Gateway exposes to us via its RESTful API. In my case, I am particularly interested in return temp of eh CV.

It is on my to do list to do something about this, either by:
 - eavesdropping on the RF signal, or
 - pulling the data from Intergas' cloud service

... both are do-able, but only with difficulty (and I have other projects on the go).

**Comment by artelse** [comment]
Thanks for response! But I don't see the fault_code in the json data?
I also run into this strange behavior where the json request is not consistent on the `heater#`. Sometimes need to pass `0` and another time `1`..

**Comment by zxdavb** [comment]
Sorry, I wasn't thinking, have edited my post, above.

> Thanks for response! But I don't see the fault_code in the json data?

For `fault_code` (for formatted JSON), use `displ_code` (from raw JSON) if `IO` (from raw JSON) is such that the following is `True`:
```python
bool(self._data["IO"] & BITMASK_FAIL)
```

Have you seen: https://www.filedropper.com/lan2rfgatewayhttpinterface ?

This may help, raw JSON:
```json
{"nodenr": 200, "ch_temp_lsb": 191, "ch_temp_msb": 15, "tap_temp_lsb": 153, "tap_temp_msb": 13, "ch_pressure_lsb": 142, "ch_pressure_msb": 0, "room_temp_1_lsb": 255, "room_temp_1_msb": 127, "room_temp_set_1_lsb": 208, "room_temp_set_1_msb": 7, "room_temp_2_lsb": 255, "room_temp_2_msb": 127, "room_temp_set_2_lsb": 255, "room_temp_set_2_msb": 127, "displ_code": 102, "IO": 2, "serial_year": 17, "serial_month": 9, "serial_line": 29, "serial_sn1": 2, "serial_sn2": 30, "serial_sn3": 82, "room_set_ovr_1_msb": 0, "room_set_ovr_1_lsb": 0, "room_set_ovr_2_msb": 7, "room_set_ovr_2_lsb": 58, "rf_message_rssi": 30, "rfstatus_cntr": 0}
```
and formatted JSON:
```json
{"display_code": 102, "display_text": "central heating", "fault_code": null, "is_burning": false, "is_failed": false, "is_pumping": true, "is_tapping": false, "heater_temp": 40.31, "tap_temp": 34.81, "pressure": 1.42, "serial_no": "1709t023082", "nodenr": 200, "rf_message_rssi": 30, "rfstatus_cntr": 0}

**Comment by zxdavb** [comment]
> I also run into this strange behavior where the json request is not consistent

I can't comment - it works for me.

**Comment by artelse** [comment]
Thanks, found the fault_code in the footnote of the document.
