### ISSUE TITLE
Lots of requirements are pinned to old versions and must be updated or unpinned

### ISSUE THREAD

**Issue by onkelbeh** [zxdavb/incomfort-client#6]
aiohttp==3.5.4 -> 3.6.2
attrs==19.1.0 -> 19.3.0 or higher
idna==2.8 -> 2.10
multidict==4.5.2 -> 4.7.6
typing-extensions==3.7.2 -> 3.7.4.3 
yarl==1.3.0 -> 1.4.2 or higher

To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version. Thanks a lot.

**Comment by zxdavb** [comment]
sorted - sorry it took so long - let me know ASAP if there are any issues, whilst I can still remember how to do it!
