### ISSUE TITLE
wrong Thermostat status in HA

### ISSUE THREAD

**Issue by KeningGruttePier** [zxdavb/incomfort-client#9]
![image](https://user-images.githubusercontent.com/52778997/222408285-438b7e0f-5208-48aa-946a-4d7aa6d18fb3.png)

I notice the thermostat card in HA dashboard is limited. 

For example if you have the heating setpoint below the current temperature it still reports 'heating' - which is wrong in my view. Could we have a little review of the issue? I was expecting the card would show "neutral" state if the setpoint is below the actual temperature reported.

**Comment by zxdavb** [comment]
This issue should be raised the [HA repo](https://github.com/home-assistant/core/issues).

However, I believe the behaviour you describe is as expected.
 - Heating enabled, rather than 
 - Heating active
